name: Deployment into VPS

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'api/**'
      - '.github/**'
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          ls -la
          . ./bin/build.sh

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/petryk/www/petryk
            git pull
            cd bin
            . ./deploy.sh
